MODELS_BY_MAKE: dict[str, tuple[str, ...]] = {
    "Daihatsu": (
        "Mira",
        "Move",
        "Terios",
        "Sirion",
        "Tanto",
        "Cast",
        "Boon",
        "Rocky",
    ),
    "Honda": (
        "Civic",
        "Accord",
        "Fit",
        "CR-V",
        "Vezel",
        "City",
        "Grace",
        "Freed",
        "Shuttle",
        "Stream",
        "Stepwgn",
        "Odyssey",
        "HR-V",
        "WR-V",
        "Insight",
        "Jazz",
        "Legend",
        "Pilot",
    ),
    "Isuzu": (
        "D-Max",
        "MU-X",
        "Elf",
        "Forward",
    ),
    "Lexus": (
        "RX",
        "NX",
        "ES",
        "IS",
        "LS",
        "GX",
        "LX",
        "UX",
        "CT",
        "RC",
    ),
    "Mazda": (
        "Axela",
        "Demio",
        "Atenza",
        "CX-3",
        "CX-5",
        "CX-8",
        "CX-30",
        "CX-60",
        "BT-50",
        "Premacy",
        "Biante",
    ),
    "Mitsubishi": (
        "Lancer",
        "Outlander",
        "Pajero",
        "Montero",
        "ASX",
        "Eclipse Cross",
        "Mirage",
        "Triton",
        "Delica",
        "Colt",
    ),
    "Nissan": (
        "March",
        "Sunny",
        "Sylphy",
        "Teana",
        "X-Trail",
        "Juke",
        "Qashqai",
        "Murano",
        "Leaf",
        "Note",
        "Serena",
        "Elgrand",
        "Navara",
        "Patrol",
        "GT-R",
    ),
    "Subaru": (
        "Impreza",
        "Legacy",
        "Forester",
        "Outback",
        "XV",
        "Crosstrek",
        "Levorg",
        "BRZ",
        "WRX",
    ),
    "Suzuki": (
        "Alto",
        "Swift",
        "Wagon R",
        "Hustler",
        "Jimny",
        "Vitara",
        "Escudo",
        "Ertiga",
        "Baleno",
        "Ciaz",
        "S-Cross",
    ),
    "Toyota": (
        "Corolla",
        "Aqua",
        "Prius",
        "Camry",
        "Vitz",
        "Yaris",
        "Allion",
        "Premio",
        "Axio",
        "Fielder",
        "RAV4",
        "Harrier",
        "Land Cruiser",
        "Prado",
        "Hiace",
        "Alphard",
        "Vellfire",
        "Noah",
        "Voxy",
        "Wish",
        "Estima",
        "CHR",
        "C-HR",
        "Fortuner",
        "Hilux",
        "Avanza",
        "Rush",
        "Raize",
        "Sienta",
        "Passo",
    ),
    "Audi": (
        "A1",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "Q2",
        "Q3",
        "Q5",
        "Q7",
        "Q8",
        "TT",
    ),
    "BMW": (
        "1 Series",
        "2 Series",
        "3 Series",
        "5 Series",
        "7 Series",
        "X1",
        "X3",
        "X5",
        "X6",
        "X7",
        "Z4",
    ),
    "Citroën": (
        "C3",
        "C4",
        "C5",
        "Berlingo",
        "DS3",
        "DS4",
    ),
    "Fiat": (
        "500",
        "Panda",
        "Punto",
        "Tipo",
    ),
    "Jaguar": (
        "XE",
        "XF",
        "XJ",
        "F-Pace",
        "E-Pace",
        "F-Type",
    ),
    "Land Rover": (
        "Defender",
        "Discovery",
        "Discovery Sport",
        "Range Rover",
        "Range Rover Sport",
        "Range Rover Evoque",
        "Range Rover Velar",
        "Freelander",
    ),
    "Mercedes-Benz": (
        "A-Class",
        "B-Class",
        "C-Class",
        "E-Class",
        "S-Class",
        "CLA",
        "CLS",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLS",
        "G-Class",
        "V-Class",
        "Sprinter",
    ),
    "MINI": (
        "Cooper",
        "Countryman",
        "Clubman",
        "Paceman",
    ),
    "Opel": (
        "Corsa",
        "Astra",
        "Insignia",
        "Mokka",
        "Crossland",
    ),
    "Peugeot": (
        "208",
        "308",
        "3008",
        "5008",
        "2008",
        "508",
    ),
    "Porsche": (
        "911",
        "Cayenne",
        "Macan",
        "Panamera",
        "Boxster",
        "Cayman",
        "Taycan",
    ),
    "Renault": (
        "Clio",
        "Megane",
        "Captur",
        "Koleos",
        "Kwid",
        "Duster",
    ),
    "SEAT": (
        "Ibiza",
        "Leon",
        "Arona",
        "Ateca",
    ),
    "Skoda": (
        "Fabia",
        "Octavia",
        "Superb",
        "Kodiaq",
        "Karoq",
        "Rapid",
    ),
    "Volkswagen": (
        "Polo",
        "Golf",
        "Jetta",
        "Passat",
        "Tiguan",
        "Touareg",
        "Beetle",
        "T-Cross",
        "T-Roc",
        "Amarok",
    ),
    "Volvo": (
        "S60",
        "S90",
        "V40",
        "V60",
        "V90",
        "XC40",
        "XC60",
        "XC90",
    ),
}
