# Generated by Django 5.2.15 on 2026-06-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='sellers/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('location_text', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
