# Generated by Django 5.2.15 on 2026-06-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
