# Generated by Django 6.0.6 on 2026-06-26 01:09

import django.db.models.deletion
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.SlugField(blank=True, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('suv', 'SUV/4x4')], max_length=16)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('trim', models.CharField(blank=True, max_length=64)),
                ('model_code', models.CharField(blank=True, max_length=64)),
                ('year_of_manufacture', models.PositiveSmallIntegerField()),
                ('year_of_registration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('brand-new', 'Brand new'), ('used', 'Used'), ('reconditioned', 'Reconditioned')], max_length=16)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], max_length=16)),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('triptronic', 'Triptronic')], max_length=16)),
                ('body_type', models.CharField(max_length=64)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=16)),
                ('hybrid_type', models.CharField(choices=[('none', 'None'), ('hybrid', 'Hybrid'), ('plug-in', 'Plug-in hybrid')], default='none', max_length=16)),
                ('drive_type', models.CharField(blank=True, max_length=64)),
                ('engine_code', models.CharField(blank=True, max_length=64)),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=64)),
                ('interior_color', models.CharField(blank=True, max_length=64)),
                ('interior_type', models.CharField(blank=True, max_length=64)),
                ('mileage_km', models.PositiveIntegerField()),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wheel_size_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tyre_size', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('features', models.JSONField(blank=True, default=list)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='sellers.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, max_length=64)),
                ('masonry_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carousel_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=vehicles.models.vehicle_photo_upload_to)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['masonry_position', 'carousel_position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehiclephoto'),
        ),
    ]
