# Generated by Django 6.0.6 on 2026-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='title',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='title_suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'All-wheel drive'), ('4x4', '4x4')], max_length=8),
        ),
    ]
