# Generated by Django 6.0.6 on 2026-06-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_title_suffix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='location',
            new_name='town',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='district',
            field=models.CharField(choices=[('colombo', 'Colombo'), ('gampaha', 'Gampaha'), ('kalutara', 'Kalutara'), ('kandy', 'Kandy'), ('matale', 'Matale'), ('nuwara-eliya', 'Nuwara Eliya'), ('galle', 'Galle'), ('matara', 'Matara'), ('hambantota', 'Hambantota'), ('jaffna', 'Jaffna'), ('kilinochchi', 'Kilinochchi'), ('mannar', 'Mannar'), ('vavuniya', 'Vavuniya'), ('mullaitivu', 'Mullaitivu'), ('batticaloa', 'Batticaloa'), ('ampara', 'Ampara'), ('trincomalee', 'Trincomalee'), ('kurunegala', 'Kurunegala'), ('puttalam', 'Puttalam'), ('anuradhapura', 'Anuradhapura'), ('polonnaruwa', 'Polonnaruwa'), ('badulla', 'Badulla'), ('monaragala', 'Monaragala'), ('ratnapura', 'Ratnapura'), ('kegalle', 'Kegalle')], default='colombo', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
