# Generated by Django 6.0.6 on 2026-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_district_and_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
