# Generated by Django 6.0.6 on 2026-06-30 05:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_exterior_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Safety', [('Airbags', 'Airbags'), ('ABS', 'ABS'), ('Traction Control', 'Traction Control'), ('Electronic Stability Control', 'Electronic Stability Control'), ('Lane Assist', 'Lane Assist'), ('Lane Departure Warning', 'Lane Departure Warning'), ('Blind Spot Monitor', 'Blind Spot Monitor'), ('Forward Collision Warning', 'Forward Collision Warning'), ('Automatic Emergency Braking', 'Automatic Emergency Braking'), ('Parking Sensors', 'Parking Sensors'), ('Reverse Camera', 'Reverse Camera'), ('360° Camera', '360° Camera'), ('Tyre Pressure Monitoring', 'Tyre Pressure Monitoring'), ('ISOFIX Child Seat Anchors', 'ISOFIX Child Seat Anchors'), ('Hill Start Assist', 'Hill Start Assist'), ('Hill Descent Control', 'Hill Descent Control')]), ('Comfort', [('Cruise Control', 'Cruise Control'), ('Adaptive Cruise Control', 'Adaptive Cruise Control'), ('Climate Control', 'Climate Control'), ('Dual Zone Climate Control', 'Dual Zone Climate Control'), ('Heated Seats', 'Heated Seats'), ('Ventilated Seats', 'Ventilated Seats'), ('Memory Seats', 'Memory Seats'), ('Power Seats', 'Power Seats'), ('Leather Seats', 'Leather Seats'), ('Sunroof', 'Sunroof'), ('Panoramic Roof', 'Panoramic Roof'), ('Keyless Entry', 'Keyless Entry'), ('Push Button Start', 'Push Button Start'), ('Remote Start', 'Remote Start')]), ('Entertainment', [('Bluetooth', 'Bluetooth'), ('Navigation', 'Navigation'), ('Radio', 'Radio'), ('CD Player', 'CD Player'), ('USB Port', 'USB Port'), ('Apple CarPlay', 'Apple CarPlay'), ('Android Auto', 'Android Auto'), ('Wireless Phone Charging', 'Wireless Phone Charging'), ('Premium Sound System', 'Premium Sound System')]), ('Driving', [('Paddle Shifters', 'Paddle Shifters'), ('Sport Mode', 'Sport Mode'), ('Drive Mode Selector', 'Drive Mode Selector'), ('Limited Slip Differential', 'Limited Slip Differential')]), ('Exterior', [('Alloy Wheels', 'Alloy Wheels'), ('Door Visors', 'Door Visors')]), ('Convenience', [('Power Windows', 'Power Windows'), ('Power Mirrors', 'Power Mirrors'), ('Auto Dimming Mirror', 'Auto Dimming Mirror'), ('Rain Sensing Wipers', 'Rain Sensing Wipers'), ('Auto Headlights', 'Auto Headlights'), ('Power Tailgate', 'Power Tailgate'), ('Tow Bar', 'Tow Bar'), ('Fog Lights', 'Fog Lights'), ('LED Headlights', 'LED Headlights')])], max_length=100, null=True), blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VehicleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('call', 'Call'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('visitor_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
