from django.db import models


class SriLankaDistrict(models.TextChoices):
    COLOMBO = "colombo", "Colombo"
    GAMPAHA = "gampaha", "Gampaha"
    KALUTARA = "kalutara", "Kalutara"
    KANDY = "kandy", "Kandy"
    MATALE = "matale", "Matale"
    NUWARA_ELIYA = "nuwara-eliya", "Nuwara Eliya"
    GALLE = "galle", "Galle"
    MATARA = "matara", "Matara"
    HAMBANTOTA = "hambantota", "Hambantota"
    JAFFNA = "jaffna", "Jaffna"
    KILINOCHCHI = "kilinochchi", "Kilinochchi"
    MANNAR = "mannar", "Mannar"
    VAVUNIYA = "vavuniya", "Vavuniya"
    MULLAITIVU = "mullaitivu", "Mullaitivu"
    BATTICALOA = "batticaloa", "Batticaloa"
    AMPARA = "ampara", "Ampara"
    TRINCOMALEE = "trincomalee", "Trincomalee"
    KURUNEGALA = "kurunegala", "Kurunegala"
    PUTTALAM = "puttalam", "Puttalam"
    ANURADHAPURA = "anuradhapura", "Anuradhapura"
    POLONNARUWA = "polonnaruwa", "Polonnaruwa"
    BADULLA = "badulla", "Badulla"
    MONARAGALA = "monaragala", "Monaragala"
    RATNAPURA = "ratnapura", "Ratnapura"
    KEGALLE = "kegalle", "Kegalle"
